language: cpp
sudo: false
branches:
  only:
    - master

addons:
  apt:
    sources:
    - avsm
    - llvm-toolchain-precise-3.8
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://download.opensuse.org/repositories/home:/ocaml/xUbuntu_14.04/ /'
      key_url: 'http://download.opensuse.org/repositories/home:ocaml/xUbuntu_14.04/Release.key'
    packages:
    - ocaml
    - m4
    - opam
    - clang-3.8
    - llvm-3.8

script: bash -ex .travis-ci.sh

cache:
  directories:
  - $HOME/.opam

notification:
  email: false
