language: c
sudo: false

before_install: 
- bash -ex .travis-ci.sh
- sudo apt-get -qq update
- sudo apt-get install -y ocaml opam

install: make

script: ./test

cache:
  directories:
  - $HOME/.opam
