language: c
sudo: required

addons:
  apt:
    sources:
    - avsm
    packages
    - ocaml
    - opam

before_install: 
- bash -ex .travis-ci.sh

install: make

script: ./test

cache:
  directories:
  - $HOME/.opam
