language: c
sudo: required

before_install: 
- sudo apt-get -qq update
- sudo apt-get install -y ocaml opam
- bash -ex .travis-ci.sh

install: make

script: ./test

cache:
  directories:
  - $HOME/.opam
