language: cpp
sudo: false
branches:
  only:
    - master

addons:
  apt:
    sources:
    - avsm
    - llvm-toolchain-precise-3.8
    - ubuntu-toolchain-r-test
    packages:
    - ocaml
    - m4
    - opam
    - clang-3.8
    - llvm-3.8

script:
  - make -C ./lib/gdchart0.94.b/
  - bash -ex .travis-ci.sh

cache:
  directories:
  - $HOME/.opam

notification:
  email: false
