language: c
sudo: required

addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex .travis-ci.sh

cache:
  directories:
  - $HOME/.opam

notification:
  email: false
